- name: Instalar unbound
  ansible.builtin.package:
    name: unbound
    state: present

- name: Habilitar Unbound no rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'unbound_enable="YES"'
    create: yes

- name: Copiar configuração do unbound
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /usr/local/etc/unbound/unbound.conf
    owner: unbound
    group: unbound
    mode: '0644'

- name: Iniciar Unbound
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true